name: Count PRs and Issues

on:
  workflow_dispatch:
    inputs:
      since:
        description: 'Date since which to count PRs and Issues'

jobs:
  count-prs-and-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Format date to ISO 8601
        id: date
        run: echo ::set-output name=isoDate::$(date -d "${{ github.event.inputs.since }}" '+%Y-%m-%dT00:00:00Z')
      - name: Count PRs and Issues
        run: node scripts/display-stats.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          since: ${{ steps.date.outputs.isoDate }}
