name: Count PRs and Issues

on:
  workflow_dispatch:

jobs:
  count-prs-and-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count PRs and Issues
        run: node scripts/display-stats.ts
