name: Count PRs and Issues

on: [pull_request, issues]

jobs:
  count-prs-and-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Count PRs and Issues
      run: node scripts/display-stats.js
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-age: '1 month'
